apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-portal-demo-deployment
  labels:
    app: patient-portal-demo
spec:
  replicas: 3
  # Deployment Strategy: RollingUpdate ensures zero downtime by updating pods incrementally
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1       # One extra pod can be created during the update
      maxUnavailable: 0 # No pods can be unavailable during the update
  selector:
    matchLabels:
      app: patient-portal-demo
  template:
    metadata:
      labels:
        app: patient-portal-demo
    spec:
      containers:
        - name: nginx-container
          image: nginx:alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "100m"
