apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: patient-portal-demo-rs
  labels:
    app: patient-portal-demo
    tier: frontend
spec:
  # This tells the ReplicaSet how many pods should be running
  replicas: 3
  # The selector defines how the ReplicaSet finds which pods to manage
  selector:
    matchLabels:
      app: patient-portal-demo
      tier: frontend
  # The template defines the pod that gets created if there aren't enough
  template:
    metadata:
      labels:
        app: patient-portal-demo
        tier: frontend
    spec:
      containers:
        - name: nginx-container
          image: nginx:alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
