apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "patient-portal.backend.fullname" . }}
  labels:
    {{- include "patient-portal.labels" . | nindent 4 }}
    component: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "patient-portal.selectorLabels" . | nindent 6 }}
      component: backend
  template:
    metadata:
      labels:
        {{- include "patient-portal.selectorLabels" . | nindent 8 }}
        component: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}/patient-portal-backend:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Values.config.name }}
            - secretRef:
                name: {{ .Values.secrets.name }}
          ports:
            - containerPort: {{ .Values.backend.containerPort }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          startupProbe:
            httpGet:
              path: /health
              port: {{ .Values.backend.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.backend.containerPort }}
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.backend.containerPort }}
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 3
