apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name | default "patient-portal-secrets" }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  MONGODB_URI: {{ .Values.secrets.mongodbUri }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret }}
  SESSION_SECRET: {{ .Values.secrets.sessionSecret }}
