apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  labels:
    {{- include "patient-portal.labels" . | nindent 4 }}
type: Opaque
data:
  MONGODB_URI: {{ .Values.secrets.mongodbUri }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret }}
  SESSION_SECRET: {{ .Values.secrets.sessionSecret }}
